---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: todo-app
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: rg.fr-par.scw.cloud/cqrs-poc/ui:0.4.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
