---
apiVersion: v1
kind: Service
metadata:
  name: cacheupdater
  namespace: todo-app
spec:
  selector:
    app: cacheupdater
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacheupdater
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cacheupdater
  template:
    metadata:
      labels:
        app: cacheupdater
    spec:
      containers:
        - name: cacheupdater
          image: cacheupdater-image:latest
          ports:
            - containerPort: 8080
