---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: todo-app
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    - protocol: TCP
      port: 443
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: bff-image:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcol:4317"
            - name: WriteApiAddress
              value: "http://writeapi:8080"
            - name: ReadApiAddress
              value: "http://readapi:8080"
