---
apiVersion: v1
kind: Service
metadata:
  name: websockethub
  namespace: todo-app
spec:
  selector:
    app: websockethub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockethub
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websockethub
  template:
    metadata:
      labels:
        app: websockethub
    spec:
      containers:
        - name: websockethub
          image: rg.fr-par.scw.cloud/cqrs-poc/websockethub:0.4.1
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: MassTransitConfig__Username
              value: guest
            - name: MassTransitConfig__password
              value: guest
            - name: MassTransitConfig__Uri
              value: rabbitmq
      imagePullSecrets:
        - name: regcred
