---
apiVersion: v1
kind: Service
metadata:
  name: readapi
  namespace: todo-app
spec:
  selector:
    app: readapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readapi
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readapi
  template:
    metadata:
      labels:
        app: readapi
    spec:
      containers:
        - name: readapi
          image: readapi-image:latest
          ports:
            - containerPort: 8080
