---
apiVersion: v1
kind: Service
metadata:
  name: websockethub
  namespace: todo-app
spec:
  selector:
    app: websockethub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websockethub
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websockethub
  template:
    metadata:
      labels:
        app: websockethub
    spec:
      containers:
        - name: websockethub
          image: websockethub-image:latest
          ports:
            - containerPort: 8080
