---
apiVersion: v1
kind: Service
metadata:
  name: bff
  namespace: todo-app
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: rg.fr-par.scw.cloud/cqrs-poc/bff:0.4.1
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector:4317"
            - name: WriteApiAddress
              value: "http://writeapi"
            - name: ReadApiAddress
              value: "http://readapi"
      imagePullSecrets:
        - name: regcred
