name: Pipeline

on:
  push:
    # todo: remove this branch
    branches: ["main", "wip/k8s"]
    paths-ignore:
      - 'README.md'
      - 'k8s/**'

env:
  IMAGE_REGISTRY: rg.fr-par.scw.cloud/cqrs-poc

jobs:
  tag:
    name: "Tag repo"
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conventional Changelog Action
        id: conventional_changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          preset: conventionalcommits
          github-token: ${{ secrets.github_token }}
          skip-commit: true
    outputs:
      version: ${{ steps.conventional_changelog.outputs.version }}

  docker:
    strategy:
      matrix:
        # image represents the name of the image produced as well as the directory containing its Dockerfile
        image: [ui, Bff, WriteApi, Handlers, CacheUpdater, ReadApi, WebSocketHub, Migrator]
    runs-on: ubuntu-24.04
    needs: tag
    steps:
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
          registry: ${{ env.IMAGE_REGISTRY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: parse tag name
        run: |
          BASETAG=${{ env.IMAGE_REGISTRY }}/${{ matrix.image }}
          echo "BASETAG=${BASETAG@L}" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.image }}/Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_REGISTRY }}/${{ matrix.image }}:latest
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.BASETAG }}:latest
            ${{ env.BASETAG }}:${{ needs.tag.outputs.version }}
